# Generated by Django 2.2.7 on 2019-11-29 12:56

from django.db import migrations, models
import django.utils.timezone
import jasmin_manage.models.requirement


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='quota',
            options={'ordering': ('consortium__name', 'resource__name')},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='requirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirement',
            name='end_date',
            field=models.DateField(default=jasmin_manage.models.requirement._five_years),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('category', 'name')},
        ),
    ]
