# Generated by Django 3.0.2 on 2020-04-01 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jasmin_manage", "0002_resourcechunk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"base_manager_name": "objects", "ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="resource",
            name="total_available",
        ),
    ]
