# Generated by Django 3.1.2 on 2020-10-29 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('jasmin_manage', '0004_auto_20201012_1039'), ('jasmin_manage', '0005_auto_20201012_1611'), ('jasmin_manage', '0006_auto_20201014_1057'), ('jasmin_manage', '0007_auto_20201023_1237'), ('jasmin_manage', '0008_collaborator_version'), ('jasmin_manage', '0009_auto_20201023_1346'), ('jasmin_manage', '0010_auto_20201029_2243'), ('jasmin_manage', '0011_auto_20201029_2250')]

    dependencies = [
        ('jasmin_manage', '0003_auto_20200401_0831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consortium',
            name='_description_rendered',
        ),
        migrations.RemoveField(
            model_name='consortium',
            name='description_markup_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='_description_rendered',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_markup_type',
        ),
        migrations.AlterField(
            model_name='consortium',
            name='description',
            field=models.TextField(help_text='Can contain markdown syntax.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Can contain markdown syntax.'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='default_consortium',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='consortium',
        ),
        migrations.AddField(
            model_name='project',
            name='consortium',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to='jasmin_manage.consortium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short resource name, used when the resource is referenced in the context of a category or service, e.g. "Disk". If not given, the full name is used in all contexts.', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='units',
            field=models.CharField(blank=True, help_text='Canonical units for the resource. Leave blank for a unit-less resource, e.g. CPUs.', max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AlterField(
            model_name='category',
            name='resources',
            field=models.ManyToManyField(related_name='categories', related_query_name='category', to='jasmin_manage.Resource'),
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('category__name', 'name')},
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(20, 'Contributor'), (40, 'Owner')], default=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', related_query_name='collaborator', to='jasmin_manage.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('project__name', 'role', 'user__username'),
                'unique_together': {('project', 'user')},
            },
        ),
    ]
