# Generated by Django 3.1.4 on 2020-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0004_auto_20201012_1039_squashed_0011_auto_20201029_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcechunk',
            name='name',
            field=models.CharField(help_text='The name of the resource chunk, e.g. QB1, QB2.', max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.SlugField(error_messages={'invalid': 'Service name can only contain letters, numbers, underscores and hyphens.'}),
        ),
    ]
