# Generated by Django 3.1.2 on 2020-10-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0005_auto_20201012_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='default_consortium',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='consortium',
        ),
        migrations.AddField(
            model_name='project',
            name='consortium',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to='jasmin_manage.consortium'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short resource name, used when the resource is referenced in the context of a category or service, e.g. "Disk". If not given, the full name is used in all contexts.', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='units',
            field=models.CharField(blank=True, help_text='Canonical units for the resource. Leave blank for a unit-less resource, e.g. CPUs.', max_length=10, null=True),
        ),
    ]
