# Generated by Django 3.1.5 on 2021-02-03 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0005_auto_20201209_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Service name must start with a letter and contain lower-case letters, numbers, underscores and hyphens only.', regex='^[a-z][-a-z0-9_]*\\Z')]),
        ),
    ]
