# Generated by Django 3.1.5 on 2021-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0006_auto_20210203_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description.', help_text='Can contain markdown syntax.'),
            preserve_default=False,
        ),
    ]
