# Generated by Django 3.1.2 on 2020-10-23 12:48

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0007_auto_20201023_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
