# Generated by Django 3.1.7 on 2021-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jasmin_manage", "0008_auto_20210217_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="consortium",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
