# Generated by Django 3.1.2 on 2020-10-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0008_collaborator_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('category__name', 'name')},
        ),
    ]
