# Generated by Django 3.2.18 on 2023-12-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_manage", "0017_auto_20231219_1100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                related_name="project",
                related_query_name="projects",
                to="jasmin_manage.Tag",
            ),
        ),
    ]
