# Generated by Django 3.2.18 on 2023-12-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0018_alter_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
