# Generated by Django 3.2.19 on 2024-02-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_manage', '0024_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
