# Generated by Django 4.2.13 on 2024-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_manage", "0027_alter_project_name_alter_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="consortium",
            name="fairshare",
            field=models.IntegerField(default=1),
        ),
    ]
