# Generated by Django 4.2.13 on 2024-10-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_manage", "0028_consortium_fairshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fairshare",
            field=models.IntegerField(default=1),
        ),
    ]
