# Generated by Django 4.2.18 on 2025-08-18 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_manage", "0029_project_fairshare"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Service name must start with a letter and contain lower-case letters, numbers, underscores and hyphens only.",
                        regex="^[a-z][-a-z0-9_]*\\Z",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Service name cannot only contain numbers.",
                        regex="^\\d*$",
                    ),
                ],
            ),
        ),
    ]
