from .category import CategoryAdmin
from .collaborator import CollaboratorAdmin
from .consortium import ConsortiumAdmin
from .invitation import InvitationAdmin
from .project import ProjectAdmin
from .quota import QuotaAdmin
from .requirement import RequirementAdmin
from .resource import ResourceAdmin
from .service import ServiceAdmin
from .tag import TagAdmin
